//Get all cases
GET http://localhost:8080/api/algs

###


//Get a single case
GET http://localhost:8080/api/algs/Aa

###


//Post a new case
POST http://localhost:8080/api/algs
Content-Type: application/json

{
    "name": "Test",
    "imageUrl": "Test",
    "recommended": "Test",
    "alternative": "Test"
}

###

//Update a case
PUT http://localhost:8080/api/algs/Aa
Content-Type: application/json

{    
    "recommended": "Test",
    "alternative": "Test"
}

###

//Delete a case
DELETE http://localhost:8080/api/algs/Aa
Content-Type: application/json

###