//Get all algs
GET http://localhost:8080/api/algs

###


//Get a single alg
GET http://localhost:8080/api/algs/2

###


//Post a new alg
POST http://localhost:8080/api/algs
Content-Type: application/json

{
    "name": "Test",
    "imageUrl": "Test",
    "recommended": "Test",
    "alternative": "Test"
}
